workspace:
  base: /go
  path: src/github.com/jpoles1/gopherbadger
pipeline:
  app:
    image: golang:1.9.2
    commands:
      - go get github.com/golang/dep/cmd/dep
      - dep ensure
      - go build
      - go test -v -cover
    environment: